### ISSUE TITLE
Создать модели

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/clients-notebook#3]
- [x] Модель с дополнительной информацией о пользователе #4
- [x] Модель услуги #5 
- [x] Модель карточки - записи на услугу #6 
- [x] Модель отзыва #7 
- [x] Паттерн генерации записей #28 
- [ ] Ссылки на соц. сети и т.п. #9
